VULCAN-326: Order csv export
mitre/vulcan pull request #327
Opened 2021-12-06 16:13 UTC by timwongj

Closes: https://github.com/mitre/vulcan/issues/326

2021-12-07 17:15 UTC, rbclark requested changes
<img width="438" alt="Screen Shot 2021-12-07 at 12 15 30 PM" src="https://user-images.githubusercontent.com/2308869/145075436-6e286dd6-d7f6-403d-b54f-ad47ec9f6734.png">

This seems to be broken for overlays (see above)

2021-12-08 19:57 UTC, timwongj commented
> 

I'm not sure if I'm missing something, but is it not supposed to be ordered by these numbers first?

<img width="438" alt="145075436-6e286dd6-d7f6-403d-b54f-ad47ec9f6734" src="https://user-images.githubusercontent.com/9956561/145275337-44b4a4c2-caf7-4217-baa6-160d4dc9b27a.png">

2021-12-08 21:02 UTC, rbclark commented
> > 
> 
> I'm not sure if I'm missing something, but is it not supposed to be ordered by these numbers first?
> 
> <img alt="145075436-6e286dd6-d7f6-403d-b54f-ad47ec9f6734" width="438" src="https://user-images.githubusercontent.com/9956561/145275337-44b4a4c2-caf7-4217-baa6-160d4dc9b27a.png">

Ah oops yeah that makes more sense I missed that.

2021-12-10 17:08 UTC, rbclark approved these changes

2021-12-10 17:08 UTC, merged