389 an alertnotification system via slack or email to notify users of mentions or actions needed combined with a way to view this in the tool
mitre/vulcan pull request #549
Opened 2023-03-16 15:38 UTC by smarlaku820

### Integrating Slack with Vulcan
Ability to send the following notification items to a private slack channel.

_Project_
- Project Creation
- Project Removal
- Project Renaming

_Component_
- Component Creation
- Component Removal

_SRG_
- SRG Upload
- SRG Removal

_Vulcan Admin_
- Assigning Vulcan Admin
- Removing Vulcan Admin

_Membership Notifications (Project)_
- Add member
- Update member role
- Remove member

_Membership Notifications (Component)_
- Add member
- Update member role
- Remove member

2023-03-16 15:41 UTC, smarlaku820 commented
Project Notifications

<img width="535" alt="project_notifs" src="https://user-images.githubusercontent.com/34048837/225671660-e26f42d0-4036-4835-a4fa-43fd0d2b8647.png">

<img width="407" alt="project_notifs_showing_links" src="https://user-images.githubusercontent.com/34048837/225671720-e69163e1-cb49-4158-9ff0-0c278e1aa105.png">

2023-03-16 15:45 UTC, smarlaku820 commented
**Project & Component Notifications**

<img width="417" alt="comp_perm_notifs" src="https://user-images.githubusercontent.com/34048837/225673202-ec22520e-da0d-4237-944d-d03f85e70e7c.png">
<img width="451" alt="project_perm_notifs" src="https://user-images.githubusercontent.com/34048837/225673224-6450b057-dbc2-44c3-a6ed-f5e888668987.png">

2023-03-16 18:13 UTC, vanessuniq requested changes
Good logic! Code needs to be more DRY. See comments for each file

2023-03-16 18:13 UTC, vanessuniq commented on app/controllers/projects_controller.rb
Need to be refactored. See suggestions on the users_controller file.  If using the private method suggested `send_slack_notification`, move it to `ApplicationController` so that you do not have to repeat yourself in other controllers. you should probably define another helper method that will take (header, icon, fields) and generate the final hash that you will use in `slack_notification_param`.  that method should also be in `ApplicationController` since it will be used in multiple controller. 
Also move `slack_notification_param` to private

2023-03-16 18:13 UTC, vanessuniq commented on app/controllers/memberships_controller.rb
see comment provided on other controllers

2023-03-16 18:13 UTC, vanessuniq commented on app/controllers/components_controller.rb
see comment provided on other controllers

2023-03-17 01:24 UTC, smarlaku820 commented on app/lib/slack_notification_fields.rb
Hi @vanessuniq,

Thanks for the comments.

I took some of the decisions of writing multi-line lambda's because of line length constraints imposed by rubocop.

rubocop was also complaining of no of lines of code in a module (must not be >100), hence I have split the fields into separate modules.

As per your suggestions on DRY, I will use the private helper methods & extract common logic. Let me see how it goes.

2023-03-17 13:03 UTC, smarlaku820 commented on app/controllers/users_controller.rb
Please check the latest push, I refactored the code .

2023-03-17 14:16 UTC, smarlaku820 commented on app/lib/slack_notification_fields.rb
Mostly refactored, let me know what you think.

2023-03-20 14:41 UTC, vanessuniq requested changes
move the `include SlackNotificationsHelper` to the `ApplicationController` so that all other controllers will automatically inherit it.

2023-03-27 17:23 UTC, vanessuniq approved these changes

2023-03-27 17:32 UTC, merged