Enabling SMTP feature to send emails via ActionMailer
mitre/vulcan pull request #584
Opened 2023-05-25 18:25 UTC by smarlaku820

- Invoking the `UserMailer` mailer via the Application Controller
- So, far the SMTP email templates have been added around reviews
- SMTP notifications will be triggered to the `project_admins` CCing the `user` requesting a review.
- `user` will be notified if the review request is `approved` or `revoked`
- If the Admins request for more changes, the `user` will also be notified of the same.

Attaching the sample screenshots

**Welcome Email**

<img width="807" alt="welcome_user_smtp" src="https://github.com/mitre/vulcan/assets/34048837/7e204f04-2171-4524-a728-a4595cdd0be3">

**Request Review**

<img width="807" alt="request_review_smtp" src="https://github.com/mitre/vulcan/assets/34048837/9dc22229-5338-4ee4-aa25-e2d56e39f004">

**Request Additional Changes**

<img width="811" alt="request_review_changes_smtp" src="https://github.com/mitre/vulcan/assets/34048837/263de719-5ca9-43de-8575-baea02e4942f">

**Approve Request**

<img width="818" alt="approve_review_smtp" src="https://github.com/mitre/vulcan/assets/34048837/cbcbe458-a06a-4956-b2de-10113cc17e5c">

**Revoke Request**

<img width="806" alt="revoke_review_smtp" src="https://github.com/mitre/vulcan/assets/34048837/a736b275-cf0a-492c-bc56-49974a9fb3b3">

2023-05-26 17:02 UTC, vanessuniq requested changes

2023-05-26 17:02 UTC, smarlaku820 commented on app/mailers/user_mailer.rb
> +    @project_id = membership_id
Hi @vanessuniq 
created an instance variable `@project_name` for reuse in the template.

2023-05-26 17:04 UTC, smarlaku820 commented on app/mailers/user_mailer.rb
> +  def parse_mailer_welcome_user_args(*args)
Yep, now based on the `membership_type` we trigger two different SMTP notifications.

**Vulcan Project Access SMTP**
<img width="800" alt="vulcan_project_access" src="https://github.com/mitre/vulcan/assets/34048837/8826ee05-0312-40c2-bb95-b05dae6e198b">

**Vulcan Component Access SMTP**
<img width="806" alt="vulcan_component_access" src="https://github.com/mitre/vulcan/assets/34048837/ebc0e336-a4aa-4af9-a169-b94ee3cd8be1">

2023-05-26 17:37 UTC, aaronlippold commented
https://github.com/excid3/noticed?? useful?

2023-05-26 18:13 UTC, smarlaku820 commented on app/mailers/user_mailer.rb
> +    @project_id = membership_id
hey @vanessuniq 
reduced the round trips now. pushed fresh changes.

2023-05-26 18:24 UTC, smarlaku820 commented
@aaronlippold , 

Thank you for suggesting the library. Although I haven't reviewed it yet, I'm open to considering it since it appears to offer extensive support for various delivery methods, which could be beneficial for our project

2023-05-26 18:27 UTC, vanessuniq commented
> https://github.com/excid3/noticed?? useful?

This could solve several delivery methods in one implementation. @smarlaku820 what do you think? I'll try to play with it.

2023-05-26 18:28 UTC, vanessuniq approved these changes

2023-05-26 18:33 UTC, vanessuniq commented
> @aaronlippold ,
> 
> Thank you for suggesting the library. Although I haven't reviewed it yet, I'm open to considering it since it appears to offer extensive support for various delivery methods, which could be beneficial for our project

@smarlaku820  Should we wait on this PR, try to use the gem Aaron suggested to see how it works out??

2023-05-26 19:52 UTC, aaronlippold commented
I always like it when others work through the hard stuff and push it into a lib for me :)

2023-05-27 00:25 UTC, smarlaku820 commented
@vanessuniq 

I haven't got the bandwidth for the next couple of weeks. Maybe, I will take a look at the lib after that.

2023-05-29 23:29 UTC, merged